### ISSUE TITLE
Questions regarding evaluation protocol

### ISSUE THREAD

**Issue by wlin-at** [saakur/EventSegmentation#1]
Hi, 

thanks for the refreshing paper and the uploaded codes. I have two questions regarding the evaluation protocol. 
In the paper, you mentioned that you “used the Hungarian matching algorithm to obtain the one-to-one mappings between the predicted segments and the ground truth to evaluate the performance”. 
In the repo, the example evaluation code `evaluateBreakfastActions.py` is used to achieve the 42.8% MoF  on the Breakfast dataset reported in the paper. 
After going through `evaluateBreakfastActions.py`, I notice that you predict boundaries for each video individually and then assign the labels to output segments and ground truth segments in ascending order (i.e. 0, 1, 2, …). Then you assume that the n-th ground truth segment always correponds to the n-th prediction. When the numbers of segments of the ground truth and the prediction for a video are not equal, then the smaller number is chosen and the extra segments on ground truth / prediction are ignored during evaluation.  I did not find any implementation of the Hungarian algorithm.
Then the IoD (intersection over detection) for each ground truth segment is computed. The final “MoF” is the IoD averaged over all the ground truth segments of one video, and then averaged over all the videos (lines 163-170 in `evaluateBreakfastActions.py`). 
However, to my understanding, MoF should be the number of correctly classified frames divided by the total number of frames on the video. 
My questions are 
1) the results reported in the paper are computed by using Hungarian matching between prediction and ground truth on each video or by assuming the “serial order correspondence” (i.e. 0,1,...n) between segments in prediction and ground truth on each video?
2) is the 42.8% the MoF value or the averaged IoD value for Breakfast?

I am really interested in the work and please correct me if there is any misunderstanding. Thank you so much for the effort!

Best regards

Wei

**Comment by pulkitkumar95** [comment]
Hey @wlin-at,


Were you able to figure out the answer to your question?

**Comment by saakur** [comment]
Hi Wei,

Thanks for the interest in our paper. Sorry for the late reply. For some reason the notifications have gone to my old email which I do not have access to anymore. See below for response. 

1. Hungarian: Our experimental setup is temporal segmentation on streaming videos where we assume that we aim to segment actions for generic actions i.e. that we do not have any notion of “classes”. So applying the Hungarian for every video would result in an inflated performance which is not a fair comparison with other approaches. Serializing the GT allows us to perform a more fair comparison and essentially does the same as the Hungarian but at each video level. We find that applying kmeans on the learned representations for “labeling” and performing the Hungarian results in similar performance. 

2. IoD: that is just an unfortunate naming convention :). It does compute the MoF. 

Thanks,
Sathya
